apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hotel-management

bases:
  - ../../base

commonLabels:
  environment: production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      kind: Deployment
      name: hotel-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: hotel-frontend
