spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  devtools:
    restart:
      enabled: false

logging:
  level:
    root: WARN
    com.hotel.management: INFO
    org.springframework.security: WARN
