apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-config
  namespace: hotel-management
data:
  SPRING_PROFILES_ACTIVE: "prod"
  CORS_ORIGINS: "https://hotelmanagement.com"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
