apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hotel-management

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: hotel-management
  app.kubernetes.io/version: "1.0.0"
