apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hotel-management-dev

bases:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: hotel-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: hotel-frontend

configMapGenerator:
  - name: hotel-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev

commonLabels:
  environment: development
